In [1]:
Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

SyntaxError: invalid syntax (<ipython-input-1-a2e525d3dfb5>, line 1)

In [2]:
import numpy as np

In [3]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]  ] )

In [4]:
b = np.array( [4, 12, -3] )

In [5]:
from numpy import linalg

In [6]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [7]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [8]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [9]:
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

SyntaxError: invalid syntax (<ipython-input-9-f0b2db90ad09>, line 1)

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(9, 0, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [12]:
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

SyntaxError: invalid syntax (<ipython-input-12-a68f9f7a8a17>, line 1)

In [13]:
np.diag(np.arange(6), k=0)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [14]:
total_sum = 0

x = np.eye(15)

for i in range(len(x[0])):
    total_sum += x[i][i]

total_sum

15.0